### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by iamwally** [jowinjohnchemban/winbinwalk#3]
Syntax error in C:\Users\John Maugeri\Desktop\binwalk script\binwalk.py
  File "C:\Users\John Maugeri\Desktop\binwalk script\binwalk.py", line 67
     <title>winbinwalk/binwalk.py at master · jowinjohnchemban/winbinwalk</title>
                                            ^
 SyntaxError: invalid character '·' (U+00B7)

**Comment by jowinjohnchemban** [comment]
Closing due to no response
